import React from 'react';

interface ResponsiveCarImageProps {
  alt: string;
  images: {
    webp: string;
    avif?: string;
    fallback: string;
    width: number;
    height: number;
  };
  className?: string;
  sizes?: string;
}

const normalizePexels = (url: string, w = 400) => {
  if (!url.includes('pexels.com')) return url;
  if (url.includes(`w=${w}`) || url.includes('w=')) return url;
  return url.includes('?') ? `${url}&auto=compress&cs=tinysrgb&w=${w}` : `${url}?auto=compress&cs=tinysrgb&w=${w}`;
};
const toPexelsWebp = (url: string) => {
  const normalized = normalizePexels(url, 400);
  if (normalized.includes('fm=webp')) return normalized;
  return normalized.includes('?') ? `${normalized}&fm=webp` : `${normalized}?fm=webp`;
};

export const ResponsiveCarImage: React.FC<ResponsiveCarImageProps> = ({ alt, images, className, sizes = '100vw' }) => {
  // Fix invalid webp URLs generated by naive .replace on pexels URLs (e.g. .png -> .webp before ? breaks)
  const rawWebp = images.webp;
  const rawFallback = images.fallback;
  const isPexels = rawFallback.includes('pexels.com');
  const fallback = isPexels ? normalizePexels(rawFallback, 400) : rawFallback;
  const webp = isPexels
    ? (rawWebp.includes('pexels.com') && rawWebp.includes('fm=webp') ? rawWebp : toPexelsWebp(fallback))
    : rawWebp;
  const placeholder = `https://via.placeholder.com/${images.width}x${images.height}?text=No+Image`;
  return (
  <picture>
    {images.avif && <source srcSet={images.avif} type="image/avif" sizes={sizes} />}
    <source srcSet={webp} type="image/webp" sizes={sizes} />
    <img
      src={fallback}
      alt={alt}
      width={images.width}
      height={images.height}
      decoding="async"
      loading="lazy"
      className={className}
      sizes={sizes}
      style={{ aspectRatio: `${images.width}/${images.height}` }}
      onError={(e) => { const t = e.currentTarget as HTMLImageElement; if (t.src !== placeholder) t.src = placeholder; }}
    />
  </picture>
  );
};
